name = "urantia-dev-api"
main = "src/index.ts"
compatibility_date = "2026-03-03"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

routes = [
  { pattern = "api.urantia.dev", custom_domain = true }
]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "9a44af1aa9224a4f8bfc4585087440dc"

[[r2_buckets]]
binding = "APP_LOGOS"
bucket_name = "urantia-app-logos"
