name = "urantia-dev-api"
main = "src/index.ts"
compatibility_date = "2026-03-03"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

routes = [
  { pattern = "api.urantia.dev", custom_domain = true }
]
